// File auto generated by structParser.py
#pragma once

#include "utils.hpp"
#include "utilsCore.hpp"
#include "memory.hpp"
#include "templateEngine.hpp"
#include "parser.hpp"
#include "verilogParsing.hpp"
#include "versat.hpp"
#include "declaration.hpp"
#include "accelerator.hpp"
#include "configurations.hpp"
#include "codeGeneration.hpp"
#include "versatSpecificationParser.hpp"
String GetRepr(LogModule* e,Arena* out);
String GetRepr(LogLevel* e,Arena* out);
String GetRepr(Subtype* e,Arena* out);
String GetRepr(CommandType* e,Arena* out);
String GetRepr(BlockType* e,Arena* out);
String GetRepr(TemplateRecordType* e,Arena* out);
String GetRepr(ExternalMemoryType* e,Arena* out);
String GetRepr(NodeType* e,Arena* out);
String GetRepr(AcceleratorPurpose* e,Arena* out);
String GetRepr(MemType* e,Arena* out);
String GetRepr(Color* e,Arena* out);
String GetRepr(VersatDebugFlags* e,Arena* out);
String GetRepr(GraphDotFormat_* e,Arena* out);
String GetRepr(DelayType* e,Arena* out);
String GetRepr(FUDeclarationType* e,Arena* out);
String GetRepr(MergingStrategy* e,Arena* out);
String GetRepr(ConnectionType* e,Arena* out);
